### ISSUE TITLE
Tag suggestion for Docker Hub project

### ISSUE THREAD

**Issue by herokang** [ellerbrock/docker-collection#2]
Hi, 
I am Kang Yin, a graduate student of Institute of Software, Chinese Academy of Sciences. Now we are doing a research on how to recommend tags for Docker Hub’s projects. We applied text mining and natural language processing to build a tag recommendation system for Docker projects.
We notice that you have created a repository on Docker Hub, which is named _ellerbrock/alpine-curl-ssl_ and the project address is [https://hub.docker.com/r/ellerbrock/alpine-curl-ssl/](https://hub.docker.com/r/ellerbrock/alpine-curl-ssl/) 
Since the developers knows their projects better, we want to evaluate our recommendation results with your help as the project developer. We want to know if the recommended tags are reasonable for your projects. 
The following tags (ranked by order) are generated from our model automatically. Would you like to do me a favor and reply with what tags are reasonable (Good) and what are not (Bad), in form of, “Good tags: ***, ***; Bad tags: ***, ***”.

The recommend tags for your project are listed as follows:

> `curl,   ssl, ellerbrock, alpine, alpine linux, ssl support, linux, processes,   security, security concerns`

It will be a great help if you can give us a feedback. 
Thank you so much for your precious time.

**Comment by ellerbrock** [comment]
hey @herokang,

since ellerbrock is my last name it won't bring some benefit for the users, what i guess they are searching for is:

- alpine
- curl
- ssl
- openssl
- unprivileged user
- https
- encryption
- download

yeah somtehing like that. its actually a pretty basic container, so i guess interest for something like that would be very small anyway. 

are you tagging the instances on docker hub or just researching?

cheers maik

**Comment by herokang** [comment]
Hey @ellerbrock,

Thanks so much for your reply. We are doing this just for research purpose. The tags you gave are great.

Your feedback information is very important for us.
